project:
  type: website
  output-dir: docs

website:
  title: "Mastering Data & AI"
  site-url: https://masteringdata.ai
  search:
    location: sidebar
    type: textbox
  reader-mode: true
  sidebar:
    title: Mastering Data & AI
    logo: /eaisi-logo.jpg    
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/showcase/eaisi/
        text: "LinkedIn profile"
      - icon: github
        href: https://github.com/eaisi
        text: "GitHub profile"
    style: floating
    collapse-level: 1
    contents:
      - section: Textbooks
        href: books.qmd
        contents:
          - text: "Introduction to Statistical Learning"
            href: books/islp.qmd
          - text: "Interpretable ML"
            href: books/iml.qmd
          - text: "Time-series forecasting"
            href: books/fpp.qmd
          - text: "Deep Learning"
            href: books/udl.qmd
      - section: Visualization with Altair
        href: altair/index.qmd
        contents:
          - text: "Curriculum"
            href: altair/curriculum.qmd
          - text: "Introduction"
            href: altair/video-altair-intro.qmd
          - text: "Grammar"
            href: altair/video-altair-grammar.qmd
          - text: "Data types"
            href: altair/video-altair-data-types.qmd
      - section: Getting into Python
        href: python/index.qmd
        contents:
          - text: "Setting up VS Code"
            href: python/vs-code.qmd
          - text: "Real Python"
            href: python/realpython.qmd
          - text: "Tour of Python"
            href: python/whirlwind.qmd
      - section: Selected papers
        href: papers.qmd
        contents: papers/*.qmd
      - section: example notebooks
        href: notebooks/index.qmd
        contents: "notebooks/**/*.ipynb"
  page-footer:
    left: |
      <br>
      © 2023 by Daniel Kapitan<br>
      This website was created with [![](/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org)<br>
      [![](/cc-by-nc-eu.png){fig-alt="CC BY-NC 4.0"}](http://creativecommons.org/licenses/by-nc/4.0/?ref=chooser-v1)<br>

format:
  html:
    theme:
      - cosmo
      - mozilla.scss
    css: styles.css
    toc: true



